### ISSUE TITLE
Google maps english only

### ISSUE THREAD

**Issue by cunhazera** [funkydan2/alpha-church#10]
I'm using the google maps in a project, but the map is always in english. I'm using here: https://github.com/cunhazera/villa-hugo/blob/master/config.toml#L119

Is there some way to change the map language?

**Comment by funkydan2** [comment]
Yep - it should be possible for us to make that an option.

According to [google's documentation](https://developers.google.com/maps/documentation/javascript/localization) maps should automatically be localised based on the user's browser. Is that working?

Overriding will be really easy...but I'll only do it if the auto-detection isn't working or isn't appropriate.

**Comment by cunhazera** [comment]
I'm accessing [this site](https://suspicious-austin-63e510.netlify.com/) but it's written _Presbyterian Church_  in english, instead of _Igreja Presbiteriana_ in portuguese. And yes, the browser is set to Brazilian Portuguese.

**Comment by funkydan2** [comment]
Ok, I think [this commit](https://github.com/funkydan2/alpha-church/commit/7e0cb234470add5bede361df13d7f92e96d35d82) enables this.

You'll need to put two more settings under `[params.map]`
```
language = "pt"
region = "BR"
```
(Not 100% sure these are the settings you want...so you'll have to play around.)

Can you let me know if this works?

----

Two more things:
1. I noticed that in your `config.toml` you've got some settings that won't get used. You can delete lines 118-122 (they're a duplicate of what is under `[params.map]`).
2. (Not regarding this issue) since you forked the project, I noticed a few problems with the SCSS with how `<h1>` and the page navigation (for the bottom of blogs and sermons) was displayed. You might want to pull in my latest commits.

**Comment by cunhazera** [comment]
Ok, thanks for the commit.

I'll change all these stuff and tell you if worked.

**Comment by cunhazera** [comment]
@funkydan2 it worked perfectly!!
