### ISSUE TITLE
Empty screen when running the app

### ISSUE THREAD

**Issue by cunhazera** [funkydan2/alpha-church#9]
I could run the server, but it only shows an empty screen when I access localhost:1313.

No erros at log.

**Comment by funkydan2** [comment]
What version of Hugo are you running? Are you running hugo to test your own site, or on the example site?

In your terminal/command prompt, make sure you're in `alpha-church/exampleSite` and run `hugo server`, then point a web browser to `localhost:1313`.

**Comment by cunhazera** [comment]
Oh, I did not know that I should run `hugo server` inside the `alpha-church/exampleSite`.
In fact, it worked when I gave the command from the `project-folder/themes/alpha-church/exampleSite`. Is it right?

**Comment by funkydan2** [comment]
I suggested you run `hugo server` on the example site so that you could see that Hugo is installed and running properly on your machine.

The reason you were getting an empty screen before is that your site (the one you're building inside `project-folder` has no content so far.

My guess is that you're new to Hugo? A good way to learn would be to put a copy of the `config.toml` file from the example site in `project-folder` and start changing some variables and see what happens. Then start putting some markdown files in the content directory (or copy some of the files from the example site and modify them).

Anyway, at this point your questions are probably more about Hugo than about this theme. Can I recommend that you pop over to the [hugo forums](https://discourse.gohugo.io) and ask your questions over there. I'm pretty active in those forums (especially helping out new users). And I'll close this issue here.

**Comment by Submersed24** [comment]
May I see the thread that you guys talked about on the Hugo Forums? I am new to Hugo as well, and trying to learn how to get it to work.

**Comment by funkydan2** [comment]
@Submersed24 I don't think a thread was started over on the Hugo forums about this...but can I reckon the same deal applies. If you want help getting started with Hugo, start a thread on the forums (maybe search for your problem first). These 'issues' are aimed for problems with this theme in particular.
